### PR TITLE
Relaxed type check of input array, to allow da.core.Array sub-classes…

### LINKED ISSUE #360: ndinterp methods fails with ResourceBackedDaskArray from aicsimageio
Hi there,

I want to use `ndinterp.affine_transform` on images loaded with aicsimageio/[nd2](https://github.com/tlambert03/nd2/issues). For some image formats (e.g. `.nd2`) aicsimageio returns a [ResourceBackedDaskAray](https://github.com/tlambert03/resource-backed-dask-array) which is an instance of `da.Array`. 

However the [type check](https://github.com/dask/dask-image/blob/b23b6156f0df36a26a007a3701e5680fbddeacab/dask_image/ndinterp/__init__.py#L86C1-L87C37) for `da.core.Array` fails.

```python
img = AICSImage("image.nd2")
affine_transform(img.dask_data, matrix)

ValueError: Array is already a dask array. Use 'asarray' or 'rechunk' instead.
```

Cheers,
Chris

### PR DESCRIPTION
**Pull request by sommerc**
For some file formats [aicsimageio](https://github.com/AllenCellModeling/aicsimageio) and [nd2](https://github.com/tlambert03/nd2/issues) return a sub-class of `da.core.Array`: [ResourceBackedDaskAray](https://github.com/tlambert03/resource-backed-dask-array)

This PR relaxes the input type check to allow da.core.Array sub-classes in ndinterp functions.

Closes #360

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

Admins can comment `ok to test` to allow this one PR to run or `add to allowlist` to allow all future PRs from the same author to run.

**Comment by m-albert** [comment]
add to allowlist

**Comment by m-albert** [comment]
Thanks for the PR @sommerc 🙏

There's an error showing up in the tests that's unrelated to this PR, so we'll need to get the associated issue https://github.com/dask/dask-image/issues/362 fixed to turn the tests green here.

**Comment by sommerc** [comment]
Thanks you @m-albert! Let me know if I can do sth.

btw. I noticed problems using current pytest >= 8.0. And had to pin pytest < 8.0. In the current version of pytest the signature of pytest.skip() has changed

**Comment by GenevieveBuckley** [comment]
> btw. I noticed problems using current pytest >= 8.0. And had to pin pytest < 8.0. In the current version of pytest the signature of pytest.skip() has changed

fyi I've fixed this particular problem in the main branch now 😄

**Review by GenevieveBuckley — APPROVED** [review]

**Comment by GenevieveBuckley** [comment]
This is a very useful change to have, thank you for contributing @sommerc 🎉

**Comment by sommerc** [comment]
Very small, but indeed usefull when data come from aicsimageio :-)

Thank you guys for your time and efforts in providing such a great resource!

**Pull request merged**
