### PR TITLE
Simplify setting meta attribute for ndmorph functions

### PR DESCRIPTION
**Pull request by GenevieveBuckley**
Marvin has pointed out a much [simpler solution here](https://github.com/dask/dask-image/pull/206#issuecomment-823902083) for https://github.com/dask/dask-image/pull/206

This is probably what I should have done in the first place.

### CODE REVIEW

**Comment by GenevieveBuckley** [comment]
Thanks @m-albert!

**Comment by GenevieveBuckley** [comment]
The local tests with cupy pass: 
```
(dask-image-dev) genevieve@genevieve-G5-5500:~/GitHub/dask-image$ conda list | grep cupy
cupy                      9.0.0b3          py38hecb4491_0    conda-forge/label/cupy_rc
(dask-image-dev) genevieve@genevieve-G5-5500:~/GitHub/dask-image$ pytest -v tests/test_dask_image/test_ndmorph/test_cupy_ndmorph.py 
============================================================================== test session starts ===============================================================================
platform linux -- Python 3.8.8, pytest-5.3.1, py-1.10.0, pluggy-0.13.1 -- /home/genevieve/anaconda3/envs/dask-image-dev/bin/python
cachedir: .pytest_cache
rootdir: /home/genevieve/GitHub/dask-image, inifile: pytest.ini
plugins: flake8-1.0.4
collected 4 items                                                                                                                                                                

tests/test_dask_image/test_ndmorph/test_cupy_ndmorph.py::test_cupy_ndmorph[binary_closing] PASSED                                                                          [ 25%]
tests/test_dask_image/test_ndmorph/test_cupy_ndmorph.py::test_cupy_ndmorph[binary_dilation] PASSED                                                                         [ 50%]
tests/test_dask_image/test_ndmorph/test_cupy_ndmorph.py::test_cupy_ndmorph[binary_erosion] PASSED                                                                          [ 75%]
tests/test_dask_image/test_ndmorph/test_cupy_ndmorph.py::test_cupy_ndmorph[binary_opening] PASSED                                                                          [100%]

================================================================================ warnings summary ================================================================================
tests/test_dask_image/test_ndmorph/test_cupy_ndmorph.py::test_cupy_ndmorph[binary_closing]
  /home/genevieve/GitHub/dask-image/dask_image/ndfilters/_utils.py:64: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
    if not isinstance(depth, collections.Sized):

tests/test_dask_image/test_ndmorph/test_cupy_ndmorph.py::test_cupy_ndmorph[binary_closing]
  /home/genevieve/GitHub/dask-image/dask_image/ndfilters/_utils.py:68: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
    if isinstance(depth, collections.Sequence):

tests/test_dask_image/test_ndmorph/test_cupy_ndmorph.py::test_cupy_ndmorph[binary_closing]
  /home/genevieve/GitHub/dask-image/dask_image/ndfilters/_utils.py:70: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
    if not isinstance(depth, collections.Mapping):

-- Docs: https://docs.pytest.org/en/latest/warnings.html
========================================================================= 4 passed, 3 warnings in 1.00s ==========================================================================
```

**Comment by m-albert** [comment]
Cool, thanks @GenevieveBuckley!

**Comment by m-albert** [comment]
Just tested my first `dask-image` merge here :)

**Comment by GenevieveBuckley** [comment]
> Just tested my first `dask-image` merge here :)

Nicely done :smile:

**Pull request merged**
