### PR TITLE
Add simple test for center_of_mass

### PR DESCRIPTION
**Pull request by Mause**
Before you submit a pull request, check that it meets these guidelines:

1. The pull request should include tests.
2. If the pull request adds functionality, the docs should be updated. Put
   your new functionality into a function with a docstring, and add the
   feature to the list in README.rst.
3. The pull request should work for Python 3.5, 3.6, and 3.7. Check
   https://travis-ci.org/dask/dask-image/pull_requests
   and make sure that the tests pass for all supported Python versions.

### CODE REVIEW

**Comment by GenevieveBuckley** [comment]
Ah, I see why you were not sure if the issue contained a legitimate bug.

So, we only see the bug if an array containing *integer values* is passed to `dask_image.ndmeasure.center_of_mass()`. The array you make in this test has float values in it, since `numpy.random.random()` [outputs arrays of float values](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.random.html).

For this test to show the bug, it would need to go something like this:
```python
a = np.random.random(shape) * 255 # multiply so values are in 8-bit range 0-255
a = a.astype(np.uint8) . # convert to unsigned 8-bit integer data
d = da.from_array(a, chunks=chunks)
```

This also means that the actual fix for the issue should also be a single line, converting the array chunks to float type before running the computation in `dask_image.ndmeasure.center_of_mass()`

**Comment by GenevieveBuckley** [comment]
I think the fix should happen in [this line](https://github.com/dask/dask-image/blob/7e8932be51a4de44ed83000f061fbcd4fe9668f4/dask_image/ndmeasure/__init__.py#L108) of  `dask-image/dask_image/ndmeasure/__init__.py`:

```python
out_dtype = numpy.dtype([("com", image.dtype, (image.ndim,))])
```
`image.dtype` needs to be changed to always be float type (instead of just reflecting the type of the input array like it does now). That's *probably* going to look like this instead:

```python
out_dtype = numpy.dtype([("com", float, (image.ndim,))])
```

**Comment by Mause** [comment]
I figured the issue was the data I was testing with, but wasn't sure how to fix it - I'll do that now

**Comment by GenevieveBuckley** [comment]
Thanks @Mause!

**Pull request merged**
