### PR TITLE
TST: Add testing to github action

### PR DESCRIPTION
**Pull request by ku-ya**
Add cron job with github actions to schedule test runs monthly/fortnightly.

Contributes to #163

### CODE REVIEW

**Comment by GenevieveBuckley** [comment]
I'm going to take a look at this later, thank you @ku-ya

**Comment by GenevieveBuckley** [comment]
Update: I've been trying to see if I can make this run every 15 minutes, but unfortunately that doesn't seem to be working on my branch? (This is the first time I have tried to schedule github actions, I might be making some mistakes)

After we can confirm it works, we can make the interval once per month and merge.

**Comment by jakirkham** [comment]
Thanks for the help @ku-ya! 🙏

We moved to GitHub Actions in PR ( https://github.com/dask/dask-image/pull/188 ). That said, if you spot anything we should add, please feel free to either update this PR to apply changes on latest `main` or open a new PR, whichever is easier.

Thanks again! 😄

**Comment by GenevieveBuckley** [comment]
I remember this from the sprint. There have been a few changes since then to the way we handle CI, so it's probably best to close this out.

Thanks for your code sprint contributions @ku-ya, it was great having you there 😄

**Pull request closed without merging**
