### PR TITLE
Support Python 3.8 with CI tests (and drop python 3.5)

### PR DESCRIPTION
**Pull request by GenevieveBuckley**
Closes https://github.com/dask/dask-image/issues/130

### CODE REVIEW

**Comment by GenevieveBuckley** [comment]
Update:
1. All the dask-image tests pass on CircleCI, the failure here is purely due to some problem with CircleCI reporting test coverage results to coveralls.io. I'm still investigating this.

2. The python 3.5 tests fail on Travis because it wasn't able to install the really old version of numpy we have pinned for this test. Instead, it falls back to a newer numpy version which is only compatible with `scikit-image>=0.14.2`
There are two possible options here: we can either bump up the pinned versions of numpy and scikit-image, or consider dropping support for python 3.5 (leaving support for 3.6, 3.7, & 3.8)

**Comment by GenevieveBuckley** [comment]
More details re: CircleCI and coveralls.io
- [x] Make sure the `COVERALLS_REPO_TOKEN` on CircleCI is set correctly.
- [x] Sync from coveralls.io then try restarting the CircleCI builds (https://coveralls.io/github/dask/dask-image/settings#lnk_alerts)
- [x] Add an empty `.coveralls.yml` file to the root of the repo
- [ ]  Add a `.coveralls.yml` file containing the token
- [ ] Check the owner of the github repo on Coveralls has up to date login credentials, try resetting them at the link https://coveralls.io/refresh?private=true (https://github.com/lemurheavy/coveralls-public/issues/703#issuecomment-175231744)

**Comment by GenevieveBuckley** [comment]
Ok great, things are working better now. 

I think we should also follow dask and drop support for python 3.5 (see https://github.com/dask/dask/issues/5478). If there are any objections against this, add a comment below.

**Comment by jakirkham** [comment]
Thanks for working on this @GenevieveBuckley! 😀

**Comment by GenevieveBuckley** [comment]
> 
> Thanks for working on this @GenevieveBuckley! 😀

You're welcome @jakirkham! We're all green now, do you want to merge this?

**Comment by chrisroat** [comment]
@GenevieveBuckley @jakirkham 

Is this ready to merge?!

**Comment by jakirkham** [comment]
Yeah sorry I dropped the ball here. Restarting CI to make sure it still passes.

**Comment by GenevieveBuckley** [comment]
I think the CI failures are unrelated, they're failing to create the conda environments - the same thing is happening over on https://github.com/dask/dask-image/pull/137. Good news is, CircleCI seems to have come good again.

I've re-started Travis after it failed just now, let's see if that's flaky or not. I can't figure out how to do the same in Appveyor, will check in again after a meeting.

**Comment by jakirkham** [comment]
I wasn’t able to restart CircleCI. Looks like it ran on your fork?

**Comment by GenevieveBuckley** [comment]
> I wasn’t able to restart CircleCI. Looks like it ran on your fork?

It looked like you did get CircleCI started, they've all passed ok.

**Comment by GenevieveBuckley** [comment]
FYI, the tests for this branch pass locally on both my Windows and Mac laptops (for all our environments across python 3.6, 3.7, & 3.8). CircleCI is testing our Linux builds and is passing.

I still don't know what the problem with the CI is. Could our version of minconda be too old now?

Travis builds passed fine [5 months ago](https://travis-ci.org/github/dask/dask-image/builds/622405744) but is [failing today](https://travis-ci.org/github/dask/dask-image/builds/622433159). Appveyor's the same.

**Comment by GenevieveBuckley** [comment]
Good instincts! Updating miniconda resolves the problems with the CI. 

I'll merge that update into this feature branch when all the builds finish running on [this PR](https://github.com/GenevieveBuckley/dask-image/pull/1).

**Comment by GenevieveBuckley** [comment]
So I see Appveyor is still listed as failing here, but it passes every time I run it on my own branch (see [build results here](https://ci.appveyor.com/project/GenevieveBuckley/dask-image/builds/32682713)).

I personally feel this shouldn't block merging, since the tests pass both locally and on Appveyor from my branch.

**Comment by jakirkham** [comment]
Thanks for wrestling with CI, Genevieve! 😄 Let's get this in 😉

**Pull request merged**
