### PR TITLE
Moved functions from ndimage submodules to ndimage namespace

### PR DESCRIPTION
**Pull request by m-albert**
This PR moves functions from the `cupyx.scipy.ndimage.filters` namespace to `cupyx.scipy.ndimage`, fixing https://github.com/dask/dask-image/issues/324.

Secondly it changes a reference to `scipy.ndimage.fourier` into `scipy.ndimage` in test functions, anticipating the [removal](https://github.com/scipy/scipy/blob/2ff5a46ec3ecc86427e73801b7c6151ed29b6dea/scipy/ndimage/fourier.py#L1C1-L3C18) of `scipy.ndimage.fourier` in scipy version 2.

### CODE REVIEW

**Comment by GenevieveBuckley** [comment]
This is great, thank you @m-albert 

I think we need a note somewhere in the docs that says what the minimum supported version of cupy is.

**Comment by GenevieveBuckley** [comment]
> I think we need a note somewhere in the docs that says what the minimum supported version of cupy is.

I've searched through the repo, and it looks like we mostly put that information in the release notes (`HISTORY.rst` file). What is the new minimum version of cupy?

And before we merge and make a new release, can I get you to check whether the pytest importerskip lines need to be updated with a different minimum version of cupy? There are [8 lines like this across the codebase](https://github.com/search?q=repo%3Adask%2Fdask-image+minversion&type=code)
`cupy = pytest.importorskip("cupy", minversion="`...

**Comment by m-albert** [comment]
Thanks @GenevieveBuckley

> And before we merge and make a new release, can I get you to check whether the pytest importerskip lines need to be updated with a different minimum version of cupy? There are [8 lines like this across the codebase](https://github.com/search?q=repo%3Adask%2Fdask-image+minversion&type=code)
cupy = pytest.importorskip("cupy", minversion="...

Good point. @rgommers [mentioned](https://github.com/dask/dask-image/issues/324#issuecomment-1635614793) that all filters were always also (and mainly) available in the `ndimage` namespace. Probably this is also true for the rest of `ndimage`?

I checked when cupyx functions first became available and updated the minversion lines. If I'm not mistaken, some versions were off, e.g. most filters were only added to cupyx in version 9.0.0 (instead of 7.7.0) and affine_transform was already available in 5.0.0 (instead of 6.0.0).

> I've searched through the repo, and it looks like we mostly put that information in the release notes (HISTORY.rst file). What is the new minimum version of cupy?

Would this be the minimum version that provides at least some functionality or the minimum version that provides all dask-image related cupy functionality?

> Do [these tests run on CI](https://gpuci.gpuopenanalytics.com/job/dask/job/dask-image/job/prb/job/dask-image-prb/127/CUDA_VER=11.5,LINUX_VER=ubuntu18.04,PYTHON_VER=3.9/testReport/tests.test_dask_image.test_ndfilters/test_cupy_ndfilters/) cover those function changes? Or is there something more we need?

@jakirkham The function changes should be covered! The reason for why the removal of `cupyx.scipy.ndimage.filters` in cupy>=11.0 hadn't been picked up must be because cupy=10.6 is installed on the GPU CI, as shown by the [console output](https://gpuci.gpuopenanalytics.com/job/dask/job/dask-image/job/prb/job/dask-image-prb/CUDA_VER=11.5,LINUX_VER=ubuntu18.04,PYTHON_VER=3.10/lastBuild/console).

**Comment by m-albert** [comment]
Probably it'd be useful to have these fixes for https://github.com/dask/dask-image/issues/324 included in the upcoming release. Do you guys think this PR is mergeable?

**Comment by GenevieveBuckley** [comment]
> Probably it'd be useful to have these fixes for #324 included in the upcoming release. Do you guys think this PR is mergeable?

Sure, I'm on board with that.
It looks like we should be fairly safe recommending people use cupy version 9.0.0 and above in the next set of release notes. Thanks for following up on this @m-albert

**Comment by jakirkham** [comment]
> It looks like we should be fairly safe recommending people use cupy version 9.0.0 and above in the next set of release notes.

Filed issue ( https://github.com/dask/dask-image/issues/328 )

**Pull request merged**
