### PR TITLE
DOCUMENTATION: Add section Talks and Slides #163

### PR DESCRIPTION
**Pull request by tkoyama010**
This is a sprint contribution in ScipyJapan2020 (#163).
I added a page to the docs with links to youtube talks and slides from previous presentations.
Thank you for reading.

### CODE REVIEW

**Comment by GenevieveBuckley** [comment]
This is nice, thank you @tkoyama010 

I would like if we could include direct links to the youtube talks as well as the repository with slides. Then people will only need to click once to watch the talks, instead of needing to search for the link on a different page.

Maybe something like:

- 2020, Genevieve Buckley's talk at PyConAU and SciPy Japan
    - Watch the talk (include youtube link, rst formatting)
    - See the slides (include a link)
- 2019, John Kirkham's SciPy talk
    - Watch the talk (include youtube link)
    - See the slides (include a link)

What do you think?

**Comment by tkoyama010** [comment]
Sounds good. +1 for it.

**Comment by tkoyama010** [comment]
@GenevieveBuckley Thanks for your review. I fixed the access to URL. It WFM.

**Review by GenevieveBuckley — APPROVED** [review]
Looks great!

**Comment by GenevieveBuckley** [comment]
🎉

**Comment by GenevieveBuckley** [comment]
@tkoyama010 I also have a link to the SciPy Japan talk recording: https://www.youtube.com/watch?v=dP0m2iZX0PU

Could you write a short sentence in Japanese that says something like: "Watch the talk (presentation in English, captions in Japanese)"

That would be very helpful also!

**Comment by tkoyama010** [comment]
Thanks. Your Japanese greetings is great :-)

**Pull request merged**
