### PR TITLE
Test `gaussian` alias

### PR DESCRIPTION
**Pull request by jakirkham**
Test the `gaussian` alias to ensure it is counted in test coverage.

### CODE REVIEW

**Comment by jakirkham** [comment]
Closing/reopening to restart CI (with latest changes from `dask/main`)

**Comment by jakirkham** [comment]
rerun tests

**Comment by GenevieveBuckley** [comment]
I see what's happening - "gaussian" was included in the `__all__` list for `dask_image/ndfilters/_guassian.py`, but it ALSO needs to be imported and in the list for the `__init__.py` file in ndfilters.

**Comment by jakirkham** [comment]
Yeah I had missed this as well. Think this is now included. Though please let me know if you spot anything else missing

**Comment by GenevieveBuckley** [comment]
...I'm going to go for a coffee and leave this alone for 5-10 minutes. I think I'm getting in the way of you working on it at the same time 😆

**Comment by GenevieveBuckley** [comment]
> Yeah I had missed this as well. Think this is now included. Though please let me know if you spot anything else missing

I guess it proves the point that there should have been a test included with the original PR, the oversight would have been very easy to catch then. But second best is doing it now, glad you're on top of it 😄

**Comment by jakirkham** [comment]
rerun tests

**Comment by GenevieveBuckley** [comment]
All the CI checks are passing, looks good!

**Comment by jakirkham** [comment]
Thanks Genevieve! 🙏

**Pull request merged**
