### PR TITLE
Create python-publish.yml

### PR DESCRIPTION
**Pull request by GenevieveBuckley**
This PR adds a github actions script to publish new releases to PyPI

### CODE REVIEW

**Comment by jakirkham** [comment]
Neat! How are the secret variables set?

**Comment by GenevieveBuckley** [comment]
You go to the dask-image settings, then the secrets tab here: https://github.com/dask/dask-image/settings/secrets

I set up an API token on PyPI, then copied the token into the github secret PYPI_PASSWORD and set PYPI_USERNAME to "__token__". 

1. Link for how to set up a PyPI API token: https://pypi.org/help/#apitoken
2. Link on how to use github secrets: https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets

Both those links came from the excellent napari release guide. I've copied and adapted those in PR https://github.com/dask/dask-image/pull/142, adding a release guide for `dask-image`.

**Comment by jakirkham** [comment]
Thanks for the details. Should we add these to a release guide?

**Comment by GenevieveBuckley** [comment]
Sure, I have a PR open with a release guide document here: https://github.com/dask/dask-image/pull/142

Feel free to edit it directly if you think it's not clear enough. You should be able to push directly to my branch. I would still like to add info on conda-forge, but it's not a big deal if we merge and then edit in a separate PR.

**Pull request merged**
