### PR TITLE
[Refactoring] making the code more Pythonic

### PR DESCRIPTION
**Pull request by maldil**
The goal of this PR is to make the code more Pythonic by utilizing Python with statements.

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

Admins can comment `ok to test` to allow this one PR to run or `add to allowlist` to allow all future PRs from the same author to run.

**Comment by GenevieveBuckley** [comment]
Hi @maldil, thanks for dropping by!
 
FYI, this file was automatically generated by [versioneer](https://github.com/python-versioneer/python-versioneer), so typically I wouldn't edit that.

https://github.com/dask/dask-image/blob/main/versioneer.py#L427-L428

If you think it's useful, you could suggest your contribution over at the main versioneer project: https://github.com/python-versioneer/python-versioneer
That way, any improvements can be used by everyone, instead of only in a single project.

**Comment by jakirkham** [comment]
It is also possible a new version of versioneer has solved this, in which case we can [upgrade]( https://github.com/python-versioneer/python-versioneer#updating-versioneer )

**Comment by GenevieveBuckley** [comment]
True, I think the versioneer version here is probably from when this repository was created.

**Comment by GenevieveBuckley** [comment]
We have versioneer version 0.18 (released September 2016) and the current version is 0.22 (released March 2022). According to the [docs](https://github.com/python-versioneer/python-versioneer/blob/master/UPGRADING.md) there is "nothing special" we need to do, other than [follow the instructions here](https://github.com/python-versioneer/python-versioneer#updating-versioneer)

**Pull request closed without merging**
