### PR TITLE
Bump dask-sphinx-theme to 1.0.4

### PR DESCRIPTION
**Pull request by jakirkham**

### CODE REVIEW

**Comment by mrocklin** [comment]
FYI I would expect several more tiny version bumps in the next couple weeks.

**Comment by jakirkham** [comment]
Makes sense. Should we worry about staying up-to-date or would it be better to wait until things settle a bit?

**Comment by mrocklin** [comment]
If the readership of dask-image was very high and the flaws in
dask-sphinx-theme were egregious (some old versions had incorrect links)
then I would say lets stay up to date.  Currently I don't think that either
of those are true and I imagine that you're busy, so in your situation I
wouldn't bother.  That's obviously a choice for you to make though :)

**Comment by jakirkham** [comment]
Ok, thanks Matt. I'll merge this one since it is here, but I'll let future ones slide until things settle or you tell me otherwise.

**Comment by jakirkham** [comment]
Should add this is another effective method to deal with package caching issues. :wink:

**Pull request merged**
