### PR TITLE
Avoid DeprecationWarnings when importing scipy.ndimage filter functions

### LINKED ISSUE #260: Deprecation warnings for import from scipy.ndimage.filters namespace
I didn't see an issue (open or closed) for this so I just wanted to make sure someone was aware. If the developers already know about this issue, go ahead and close this.

**What happened**:

Importing `dask_image.ndfilters` causes `DeprecationWarning`s to be issued. The warnings are issued because the filter functions that dask-image uses have all been moved to the `scipy.ndimage` namespace from `scipy.ndimage.filters` which will be removed in scipy 2.0. Because dask-image imports most, if not all, of the filter functions, a lot of warnings pop up when `dask_image.ndfilters` is imported.

**What you expected to happen**:

No `DeprecationWarning`s.

**Minimal Complete Verifiable Example**:

```python
import warnings
warnings.simplefilter('always', DeprecationWarning)
import dask_image.ndfilters

/home/USER/anaconda3/envs/rstools/lib/python3.8/site-packages/dask_image/ndfilters/_conv.py:15: DeprecationWarning: Please use `convolve` from the `scipy.ndimage` namespace, the `scipy.ndimage.filters` namespace is deprecated.
  @_utils._update_wrapper(scipy.ndimage.filters.convolve)
/home/USER/anaconda3/envs/rstools/lib/python3.8/site-packages/dask_image/ndfilters/_conv.py:42: DeprecationWarning: Please use `correlate` from the `scipy.ndimage` namespace, the `scipy.ndimage.filters` namespace is deprecated.
  @_utils._update_wrapper(scipy.ndimage.filters.correlate)
/home/USER/anaconda3/envs/rstools/lib/python3.8/site-packages/dask_image/ndfilters/_diff.py:14: DeprecationWarning: Please use `laplace` from the `scipy.ndimage` namespace, the `scipy.ndimage.filters` namespace is deprecated.
  @_utils._update_wrapper(scipy.ndimage.filters.laplace)
/home/USER/anaconda3/envs/rstools/lib/python3.8/site-packages/dask_image/ndfilters/_edge.py:24: DeprecationWarning: Please use `prewitt` from the `scipy.ndimage` namespace, the `scipy.ndimage.filters` namespace is deprecated.
  @_utils._update_wrapper(scipy.ndimage.filters.prewitt)
/home/USER/anaconda3/envs/rstools/lib/python3.8/site-packages/dask_image/ndfilters/_edge.py:42: DeprecationWarning: Please use `sobel` from the `scipy.ndimage` namespace, the `scipy.ndimage.filters` namespace is deprecated.
  @_utils._update_wrapper(scipy.ndimage.filters.sobel)
/home/USER/anaconda3/envs/rstools/lib/python3.8/site-packages/dask_image/ndfilters/_gaussian.py:58: DeprecationWarning: Please use `gaussian_filter` from the `scipy.ndimage` namespace, the `scipy.ndimage.filters` namespace is deprecated.
  @_utils._update_wrapper(scipy.ndimage.filters.gaussian_filter)
/home/USER/anaconda3/envs/rstools/lib/python3.8/site-packages/dask_image/ndfilters/_gaussian.py:101: DeprecationWarning: Please use `gaussian_gradient_magnitude` from the `scipy.ndimage` namespace, the `scipy.ndimage.filters` namespace is deprecated.
  @_utils._update_wrapper(scipy.ndimage.filters.gaussian_gradient_magnitude)
/home/USER/anaconda3/envs/rstools/lib/python3.8/site-packages/dask_image/ndfilters/_gaussian.py:129: DeprecationWarning: Please use `gaussian_laplace` from the `scipy.ndimage` namespace, the `scipy.ndimage.filters` namespace is deprecated.
  @_utils._update_wrapper(scipy.ndimage.filters.gaussian_laplace)
/home/USER/anaconda3/envs/rstools/lib/python3.8/site-packages/dask_image/ndfilters/_generic.py:14: DeprecationWarning: Please use `generic_filter` from the `scipy.ndimage` namespace, the `scipy.ndimage.filters` namespace is deprecated.
  @_utils._update_wrapper(scipy.ndimage.filters.generic_filter)
/home/USER/anaconda3/envs/rstools/lib/python3.8/site-packages/dask_image/ndfilters/_order.py:21: DeprecationWarning: Please use `minimum_filter` from the `scipy.ndimage` namespace, the `scipy.ndimage.filters` namespace is deprecated.
  @_utils._update_wrapper(scipy.ndimage.filters.minimum_filter)
/home/USER/anaconda3/envs/rstools/lib/python3.8/site-packages/dask_image/ndfilters/_order.py:48: DeprecationWarning: Please use `median_filter` from the `scipy.ndimage` namespace, the `scipy.ndimage.filters` namespace is deprecated.
  @_utils._update_wrapper(scipy.ndimage.filters.median_filter)
/home/USER/anaconda3/envs/rstools/lib/python3.8/site-packages/dask_image/ndfilters/_order.py:75: DeprecationWarning: Please use `maximum_filter` from the `scipy.ndimage` namespace, the `scipy.ndimage.filters` namespace is deprecated.
  @_utils._update_wrapper(scipy.ndimage.filters.maximum_filter)
/home/USER/anaconda3/envs/rstools/lib/python3.8/site-packages/dask_image/ndfilters/_order.py:102: DeprecationWarning: Please use `rank_filter` from the `scipy.ndimage` namespace, the `scipy.ndimage.filters` namespace is deprecated.
  @_utils._update_wrapper(scipy.ndimage.filters.rank_filter)
/home/USER/anaconda3/envs/rstools/lib/python3.8/site-packages/dask_image/ndfilters/_order.py:131: DeprecationWarning: Please use `percentile_filter` from the `scipy.ndimage` namespace, the `scipy.ndimage.filters` namespace is deprecated.
  @_utils._update_wrapper(scipy.ndimage.filters.percentile_filter)
/home/USER/anaconda3/envs/rstools/lib/python3.8/site-packages/dask_image/ndfilters/_smooth.py:17: DeprecationWarning: Please use `uniform_filter` from the `scipy.ndimage` namespace, the `scipy.ndimage.filters` namespace is deprecated.

```

**Anything else we need to know?**: Currently this doesn't show up in during normal usage but pytest picks up the warnings.

**Environment**:

- Dask version: 2023.03.0
- Python version: 3.8.13
- Operating System: Ubuntu 21.10
- Install method (conda, pip, source): conda

<details>
<summary>Cluster Dump State:</summary>

</details>

### PR DESCRIPTION
**Pull request by fbunt**
Fix #260 

Import from `scipy.ndimage` rather than `scipy.ndimage.filters` as the filters namespace is now deprecated.

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by jakirkham** [comment]
ok to test

**Comment by fbunt** [comment]
Hmm It looks like i missed some based on the test output

**Comment by fbunt** [comment]
Looks like I got all of the filters DeprecationWarnings. `scipy.ndimage.fourier` has the same issue though. Would you like me to do the same for that namespace? The fourier functions appear to have been importable from the `scipy.ndimage` namespace at least as far back as 0.19.1 as well.

**Comment by fbunt** [comment]
I don't think the docs build CI failure is due to my changes. It seems to happen regardless. I found these: https://github.com/sphinx-doc/sphinx/issues/10291, https://github.com/readthedocs/readthedocs.org/issues/9038

**Comment by GenevieveBuckley** [comment]
Thank you for the PR @fbunt!

I agree, I think the docs build failure is unrelated. I suspect the `environment_doc.yml` file is very old, and we might need to update the version numbers in it.

**Comment by GenevieveBuckley** [comment]
Let's try [the same fix suggested here](https://github.com/sphinx-doc/sphinx/issues/10291#issuecomment-1078046986)

> Pinning to `Jinja2<3.1` fixed it for our project. At first I thought 3.0.3 broke it too until I saw something else undoing my pin in the log; you should check again.

The CI tests are running again now, so if they all pass this time we should be ready to merge this PR.

**Comment by fbunt** [comment]
Thanks!

**Comment by jakirkham** [comment]
Thank you both! 🙏

**Pull request merged**
