### PR TITLE
Add function coverage table to the dask-image docs

### PR DESCRIPTION
**Pull request by abhisht51**
Hi, 
I have added the table in a new file called 'comparision.rst' 
Feel free to make suggestions
Thanks 
#154

### CODE REVIEW

**Comment by Sh4zKh4n** [comment]
Thanks for adding in the line about what can be used directly!

**Review by GenevieveBuckley — CHANGES_REQUESTED** [review]
Thanks @abhisht51, this is great!

1. Both headings in this file have the word coverage in them, do you mind if we call this file `coverage.rst` instead? We could do that with "git mv compirision.rst coverage.rst"
2. Add a link to this page from `index.rst`, so that users looking at our website can find the page. I think if you edit `docs/index.rst` and add a line to the table of contents that should do it. Probably it should end up looking like this:
```
.. toctree::
   :maxdepth: 1

   installation
   quickstart
   coverage
   api
   contributing
   authors
   history
```

I haven't tried to check the ReST formatting, I'm assuming that it's good. Thanks again!

**Review by GenevieveBuckley — APPROVED** [review]
Looking good! I plan to merge this shortly.

**Comment by GenevieveBuckley** [comment]
Merged! Thank you for your work @abhisht51

**Comment by Sh4zKh4n** [comment]
Yes agree with @GenevieveBuckley, thanks @abhisht51 , you guys are invaluable and wanted to say my thanks.

**Pull request merged**
